### ISSUE TITLE
我在使用Typescript，如何更好的对crypto-js-wasm进行声明？

### ISSUE THREAD

**Issue by vsme** [originjs/crypto-js-wasm#1]
无法找到模块“@originjs/crypto-js-wasm”的声明文件。

**Comment by PeterAlfredLee** [comment]
目前crypto-js-wasm还未使用TS，因此没有相关的类型声明文件
相关的类型声明开发，我刚更新到了roadmap中，也欢迎提交PR :)

**Comment by vsme** [comment]
目前我是这么处理的，拉取了 @types/crypto-js 仓库：
```ts
declare module '@originjs/crypto-js-wasm' {
  import CryptoJS from '@types/crypto-js';
  export default CryptoJS
}
```
修改了文件
node_modules\@types\crypto-js\index.d.ts

160行: 
HasherHelper  增加:
```ts
loadWasm: () => Promise<unknow>;
```

520行:
CryptoJS 增加
```ts
export const loadAllWasm: () => Promise<unknow>;
```

虽然能正常工作了，但不优雅。

**Comment by vsme** [comment]
还是等你们来处理吧

**Comment by PeterAlfredLee** [comment]
crypto-js-wasm的API与crypto-js还有少量区别，并且我们后续还会支持RSA等算法，直接使用crypto-js的types体验不好也不优雅

后续我们会提交相关的TS types到types组织的[DefinitelyTyped]https://github.com/DefinitelyTyped/DefinitelyTyped)，到时大家就可以顺利使用，预计8月份可以完成

**Comment by PeterAlfredLee** [comment]
> crypto-js-wasm的API与crypto-js还有少量区别，并且我们后续还会支持RSA等算法，直接使用crypto-js的types体验不好也不优雅
> 
> ~~后续我们会提交相关的TS types到types组织的[DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) 到时大家就可以顺利使用，预计8月份可以完成~~

我们当前已经通过内置TypeScript类型的方式，发布了支持TypeScript的beta版本，预计8月份将发布支持RSA和TypeScript的1.1.0版本

**Comment by PeterAlfredLee** [comment]
1.1.0版本已经发布，已经支持了TypeScript :)

**Comment by tomandx266** [comment]
文件分块updete方法不可用吗

**Comment by tomandx266** [comment]
文件分块updete方法不可用吗****

**Comment by PeterAlfredLee** [comment]
@tomandx266 
你好，如果有需要，可以新提一个issue，并提供详细一点的信息，感谢
