### ISSUE TITLE
Connecting the library to the postman

### ISSUE THREAD

**Issue by AdrianusWest** [originjs/crypto-js-wasm#16]
Is it possible to add the entire library to the repository in one file to be able to plug it remotely into postman and its pre-request script?
Or can you tell me how I can connect your library to postman?

**Comment by PeterAlfredLee** [comment]
Hi @AdrianusWest 
I think you are talking about integrating `crypto-js-wasm` into `postman`. I'm not familiar with postman, so I can not help you with the integration with postman.

```
Is it possible to add the entire library to the repository in one file
```
Yes, of course. You can achieve this with `npm run build` and find the `index.js` in directory `lib`. But I do not think this can do any help with the integration with postman.

**Comment by AdrianusWest** [comment]
Hi, @PeterAlfredLee!
Thanks for the reply. Unfortunately, postman doesn't allow you to plug in the required libraries, so the question wasn't quite correct from the beginning.
