### ISSUE TITLE
RSA加密后呈现为Unit8Array!!转换字符串不成功

### ISSUE THREAD

**Issue by itmanyong** [originjs/crypto-js-wasm#5]
示例代码：
```js
const rsa = new C.algo.RSA();

await rsa.loadWasm();
let encrypted = rsa.encrypt('mesage');

let enStr = String.fromCharCode.apply(null, new Uint16Array(encrypted))
```
转换后的结果如下：前面是encrypted,后面是enStr
![image](https://user-images.githubusercontent.com/53500371/212484377-78b4b574-715f-44c4-b95e-7d23998997d2.png)

- 转换的 enStr 应该不属于预期的结果
- encrypted如何才能得到字符串结果呢

**Comment by PeterAlfredLee** [comment]
为何要获取字符串结果呢？
rsa加密后的二进制内容，不是按任何字符编码保存的，正常是不能以字符串的方式展示的
如果需要将二进制内容以字符串结果展示，可以考虑base64编码

**Comment by itmanyong** [comment]
> 为何要获取字符串结果呢？ rsa加密后的二进制内容，不是按任何字符编码保存的，正常是不能以字符串的方式展示的 如果需要将二进制内容以字符串结果展示，可以考虑base64编码

考虑字符串是为了方便存储、各方之间方便传递。也比较符合人的正常思维。
base64是个不错的方案，感谢提供思路
