### ISSUE TITLE
AES encryption has different result between crypto-js and crypto-js-wasm

### ISSUE THREAD

**Issue by yckbilly1929** [originjs/crypto-js-wasm#8]
Example code below:

```
await CryptoJSW.AES.loadWasm()

const block = CryptoJSW.AES.encrypt(JSON.stringify(res), encKey, {
    iv: encKey,
    mode: CryptoJSW.mode.CBC,
    padding: CryptoJSW.pad.Pkcs7,
  })
  const data = block.ciphertext.toString(CryptoJSW.enc.Hex)
```

After switching from crypto-js to crypto-js-wasm, the ciphertext changed.

**Comment by PeterAlfredLee** [comment]
Hi @yckbilly1929 
Thanks for your reporting.

We have some tests against the difference between `crypto-js` and `crypto-js-wasm`. You can check them out [here](https://github.com/originjs/crypto-js-wasm/blob/main/test/crypto-js-test/algo.aes.test.js).

For your case, as you didn't provide detailed test data, I tested it like this:
```javascript
const key256 = cryptoJs.enc.Hex.parse('000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f');
const iv = cryptoJs.enc.Hex.parse('101112131415161718191a1b1c1d1e1f');

test('testIssue8', () => {
  const block = cryptoJs.AES.encrypt('Test', key256, {
    iv: iv,
    mode: cryptoJs.mode.CBC,
    padding: cryptoJs.pad.Pkcs7,
  });
  const data = block.ciphertext.toString(cryptoJs.enc.Hex);
  
  const block1 = cryptoJsWasm.AES.encrypt('Test', key256, {
    iv: iv,
    mode: cryptoJsWasm.mode.CBC,
    padding: cryptoJsWasm.pad.Pkcs7,
  });
  const data1 = block.ciphertext.toString(cryptoJsWasm.enc.Hex);

  expect(data).toEqual(data1);
});
```

This testcase was successfully finished.

Maybe you could provide some detailed information? :)

**Comment by yckbilly1929** [comment]
Sorry for any inconvenience caused. Cannot reproduce on my side too. 

I guess we can close the issue. ✊
